---
title: Media Law Midterm
---

*An essay I completed in fall of 2022 about Texas's House Bill 20, as a midterm for my media law class.*

### Background
In 2021, the Texas House of Representatives passed Texas House Bill 20, typically shortened to HB 20, a law which prohibits social media platforms from discriminating against user-generated content based on viewpoint. The title of the legislation is, “An Act Relating to censorship of or certain other interference with digital expression, including expression on social media platforms or through electronic mail messages,” which reveals the motivation behind the law; the Texas House of Representatives seeks to prevent perceived political censorship on social media.
The law defines censorship more explicitly, and states that platforms may not “edit, alter, block, ban, delete, remove, deplatform, demonetize, de-boost, regulate, restrict, inhibit the publication or reproduction of, or deny equal access or visibility to expression, to suspend a right to post, remove, or post an addendum to any content or material posted by a user, or to otherwise discriminate against expression.” A social media platform under HB 20 is defined to include search engines, websites, systems, and software providers, so long as they are open to the public, allow platform users to create an account, and enable users to communicate with other users by posting content. The law is specified to apply only to platforms with greater than 50 million monthly American users. It is a broad-reaching definition that captures a great deal of what might be considered “the internet.” HB 20 does not, however, deign to define what content might be considered a user’s “viewpoint.” 
After the law was passed, the organization of internet corporations known as NetChoice and the Computer & Communications Industry Association sued Texas Attorney General Ken Paxton. In September of 2022, the Fifth Circuit Court of Appeals released their ruling, which found the law to be constitutional. The Eleventh Circuit Court of Appeals found a similar law in Florida to be unconstitutional in the case NetChoice v. Attorney General, State of Florida. The Supreme Court will examine the law soon, and in the meantime, HB 20 has been suspended pending appeal. 

### Fifth Circuit Holding
The Fifth Circuit court holds that HB 20 does not infringe on any First Amendment rights held by the platforms. The court emphasized the distance between platforms and their user-generated content; platforms can “say whatever they want to distance themselves from the speech they host.” Unlike social media, traditional media forms involve a great deal of editorial discretion. Newspapers, for example, are held responsible for the speech of their writers, and therefore, the newspaper itself enjoys some related First Amendment protections, as well as some responsibilities. Platforms’ relationship to their content is entirely different. The Fifth Circuit holds that platforms “exercise virtually no editorial control or judgement.” This characterization separates mere content moderation from constitutionally protected speech, in the Fifth Circuit’s view. 
The Fifth Circuit believes that in order to strike the law as unconstitutional under the First Amendment, the law must either compel or restrict the platform’s speech. Having determined that content moderation is not speech in and of itself, there was no further ground for arguing that the law contained an unconstitutional mandate. 

### Issue 1. The language of HB 20 is not precise enough with regard to platform. 
The question of whether platforms have a “right” to censor is a critically important one, but HB 20 appears patently unconstitutional before that inquiry even needs to be addressed. Its language is far too broad to be acceptable of any law even incidentally curtailing speech. 
The terms outlined in HB 20 appear to be more restrained than they actually are. Prohibiting “social media” “censorship” based on “viewpoint” sounds at face like a legitimate government interest. Fostering productive discussion and innovation was the entire purpose behind Section 230. The state has an interest in keeping Internet discussion free, unchilled, and diverse, and preventing individuals from having their Tweets or YouTube videos hidden due only to their political affiliation is a reasonable concern. 
This, however, is not the only type of communication HB 20 targets. For example, banning the modification of a community-generated forum to remove or correct incorrect, biased, or misleading information presented as fact – such as that which might appear on Wikipedia – is not a compelling or even genuine government interest. And yet, HB 20’s language explicitly says that platforms may not “edit” or “alter” user-generated content on any platform with greater than 50 million users that, “is open to the public, allows a user of the platform to create an account, and enables a user to communicate with other users for the primary purpose of posting information, comments, messages, or images.”
An even cursory glance at the definitions of the terms provided in HB 20 reveals that the law tumbles headlong into unexpected sections of internet communication. Those arguing for the law’s constitutionality must not only be held to explaining the government’s interest in protecting political speech in the arena of public discourse, but also in sections of the internet where user-generated content is detached from the user and/or presented as fact alone. 
In order to be constitutional, the law would first have to be more carefully tailored to exclude online media where the purpose of posting content is informational, rather than for discussion. Wikipedia still serves as a great example; there should be no doubt that Wikipedia has the right to edit or clarify incorrect information on their platform, because the entire purpose of the platform is the presentation of fact. Does the government have a genuine and important interest in protecting viewpoint-based speech that is intended not to enrich discourse, but only to deceive? Such would be the effect on a number of platforms. If not, HB 20 appears unconstitutional under intermediate scrutiny, as the Fifth Circuit used in their examination of the law in September.  

### Issue 2. The language of HB 20 is not precise enough with regard to viewpoint. 
A great deal of the language in HB 20 is painstakingly defined – “social media,” “censorship,” “user,” “expression,” and even “receive” are all examples. One term is conspicuously absent; nowhere does HB 20 define what is meant by “viewpoint,” which ought to be the most important term in the entire law. 
“Viewpoint” could, and likely does, refer to a broad variety of content, such as religious, social, or political speech. It likely includes the subjects usually implicated in First Amendment discussion. However, viewpoints could also be interpreted to include a wide range of other beliefs and opinions, from international politics to pop culture and everything in between. In that case, the word itself becomes universal, and consequently meaningless. If all content is “viewpoint-based,” HB 20 seeks to prohibit the censorship of all content. 
Indeed, it is harder to imagine content that does not conceivably implicate some sort of value or framework. A photograph of a family pet could imply a “viewpoint” about animal rights. 
This ambiguity raises another important question: is HB 20 content-based? The Fifth Circuit held that the law was not content-based, but surely the difference between a post espousing a certain viewpoint and a post with no viewpoint is a content-based distinction. It is impossible to be sure without a definition of the word.
To the law’s credit, the word “viewpoint” could be deliberately undefined, in order to emphasize the breadth of speech HB 20 seeks to protect. In this case, determining what censorship is “viewpoint-based” would be left to the platforms themselves, and to the courts when the law comes into effect. This is not a valid defense of the language’s lack of clarity, however, since the Supreme Court has stricken down laws for this very reason. 
Legislative vagueness can be a violation of the Constitution. The Court ruled in Connally v. General Construction Co. that a law is unconstitutionally vague if a person “of common intelligence must necessarily guess at its meaning.” The Supreme Court has held that vague legislation poses a threat to due process, enables arbitrary discrimination on the part of law enforcement, and chills lawful exercise of First Amendment rights, all three of which are of concern in the case of HB 20.  
In that case, the Texas House’s motivation behind the lack of clarity in HB 20 is moot, because it fails to anticipate the myriad issues that may arise as a result. It is not difficult to imagine a scenario in which language favorable to the state is deemed to contain some kind of “viewpoint,” while that which is not is left unprotected. Conversely, a vindictive state could choose to interpret any moderation at all as hostile viewpoint-based censorship, in order to take punitive swipes at a platform of which they did not approve. A platform could halt all content moderation in order to avoid running afoul of HB 20, subjecting users to the kind of “toxic” environment previous legislation like Section 230 sought to prevent; spam, which is commonly filtered out by algorithms, could very well be viewpoint-motivated, if it has some sort of political, social, or religious agenda. 
The Court should find that HB 20 is improperly tailored to address the government interest it intends to suit, by potentially including all user-generated content, and contains unconstitutionally vague language. 

### Issue 3. The Caveat
Accepting that HB 20 runs afoul of constitutionality because of its language, the Supreme Court could, hypothetically, strike the law down without making any comment on censorship. 
However, it ought to be said that the Platforms’ assertion that government prohibition of political censorship is a violation of their free speech rights is ridiculous. The Fifth Circuit, though flawed in their analysis, made a number of important observations in their discussion of HB 20. 
First, no reasonable user of a platform would mistake an individual’s post for the beliefs of the platform. On platforms of the scale that HB 20 targets, content contradicts itself. To pick out a single post or attitude and say that it reflects the will of a platform is to disregard the volume of other content found there. Moreover, as the Fifth Circuit pointed out, HB 20 does nothing to prevent platforms from making their own statements regarding the content on their sites.
Functionally, a social media site hosting a user’s speech is not perceived as speech on the part of the site, and therefore should not be governed in that manner. 
Second, the First Amendment was not written with this scenario in mind. Over the last 200 years, the street-corner, protected by the First Amendment, has become a less effective site for speech than the privately-owned Platform. Public speech is now dependent on the benevolence of private corporations, rather than the benevolence of the government. The Fifth Circuit acknowledges that the government cannot compete with private platforms in providing internet space for public discourse. What is left for governments looking to secure public free speech for individuals? They can only hope to impart upon corporations – by culture or by legislation – the same values to which they themselves are held. 
The purpose of the First Amendment was to protect private citizens from government censorship. The question now is which part of that objective the Court finds more important: the rights of the private, or the protection from censorship – whether it chooses to prioritize the rights of companies, or of citizens. Social media platforms self-regulate in ways that affect the everyday lives of millions of Americans. These are not elected officials, not subject to the accountability we expect of our government, and not beholden to any objectives above profit.  
There is no enshrined right for a social media platform to censor its users, yet, even though it is broadly held that some moderation is acceptable. Corporations do have certain protected free speech rights; cases such as Citizens United v. Federal Election Commission and Burwell v. Hobby Lobby Stores, Inc. indicate as much. It is reasonable to argue that the prioritization of certain content at the expense of other content is expressive; it is reasonable to argue that censorship itself is expressive. 
It is clear that, as of yet, censorship exists in a grey area. On its face it infringes upon the behavior of private citizens, but is itself a private action. The most dangerous thing that the Supreme Court could do would be to take HB 20 as an opportunity to codify censorship as a right. Private companies have in the past and will continue to vie for this, but acquiescing would be a mistake. 
To the extent that the government can protect First Amendment rights in the private sphere, it has a vested interest to do so. If the Supreme Court grants any ground to the platforms claiming they have a right to censorship, they surrender free speech itself to the hands of corporations. 
