---
title: Story Examples
editor: 
  markdown: 
    wrap: sentence
---

## Georgetown HFC Story

*This is a piece I wrote for my advanced news reporting class in the fall of 2022.*

Students at Georgetown University will be the only source of contraceptives on campus for their peers this fall.
Georgetown University, a Catholic institution, has never provided students with worn or pharmaceutical contraceptives.
That role has been taken up by H\*yas for Choice, a student group not officially recognized by the university.

H\*yas for Choice was founded under the name GU Choice in 1991.
Reporting from the school newspaper, The Hoya, and several others, indicates that Georgetown administration initially recognized the club but sparked a backlash from the student and faculty communities.
The opposition culminated in requests for a canon suit submitted to Pope John Paul II to revoke the school\'s Catholic status, which caused school administrators to disavow the student organization in 1992.
H\*yas for Choice has operated outside of Georgetown University\'s recognition ever since.

Members said that since they receive no funding from the institution, they operate on donations and sometimes pay out of pocket to supply GU students with contraceptives.
Being unaffiliated with the school also requires the asterisk in the club\'s name -- according to the H\*yas for Choice website, the term \"hoya\" is trademarked by Georgetown University, so outside organizations are prohibited from using it.

When asked about H\*yas for Choice and the school\'s contraceptives policy, Georgetown University representatives made no comment.

Emma Barenbaum, a junior member of H\*yas for Choice, said that one of the club\'s methods is to encourage students to become \"condom ambassadors\" by hanging envelopes containing condoms on the outside of their dorm room door.

\"Legally, the university can\'t touch, can\'t take down anything we put on the doors, because the doors are considered our property while we\'re living in there,\" Barenbaum said.

Junior H\*yas for Choice member Marieteresa Porcher said that the club also offers the emergency contraceptive pill known as Plan B. Students can email the club and meet with one of its members to get the pill.
Porcher said that there was \"no judgement\" for students asking for Plan B.

Porcher said that H\*yas for Choice also makes use of free speech policies on campus to set up a table in Red Square, a space often used for protest.
Students have historically been able to stop by the table to pick up lubricant, condoms, and informational materials.
Last week, H\*yas for Choice offered humorous boxed condoms with pictures of endangered species on them.

\"Right now, our condoms say, \'extinction is forever -- wear a condom,\' because of overpopulation,\" Barenbaum said, \"So, avoid procreating so the animals can procreate.
We try to add a little bit of funniness into it.\"

Barenbaum and Porcher both said that their club has a generally positive relationship with the student body, though the school does have a significant anti-abortion population.

Students in H\*yas for Choice and in GU\'s Right to Life club said that the Supreme Court\'s decision in Dobbs v. Jackson Women\'s Health Organization this summer raised the stakes on GU\'s campus.
The Right to Life club has no official stance on contraception, but members emphasized Georgetown\'s history as a Catholic institution.

\"Catholic universities should promote that culture of life and dignity for all students,\" said Alissa Keegan, president of GU Right to Life.
Keegan said that GU Right to Life is a service-oriented club that focuses on supporting young mothers and advocating against abortions.
Keegan said GU Right to Life does receive funding from Georgetown University and that the club\'s budget is handled and approved by a student advisory board.

Keegan said H\*yas for Choice is a relatively popular club on campus, and anti-abortion attitudes at GU were \"more prevalent than you\'d expect at a Catholic university.\"

Elizabeth Oliver, a freshman representative in GU Right to Life, said that the school\'s religious affiliation is a significant presence for students.
\"There are Jesuit values all over campus,\" she said.

\"Georgetown is a Catholic school.
Students who go to Georgetown know that,\" Oliver said.

Oliver said that GU, being in DC, was in a \"tricky position.\" GU is the largest school in DC which does not offer contraceptives of any kind to its students.
Being in a city which appears largely pro-abortion creates some tension on campus, Oliver said, but she said she also believes that GU should continue to assert their religious commitment, even if it is unpopular.

\"The Jesuit tradition has always been about education, going out and teaching people, and bringing people in,\" Oliver said.
 

The Catholic University of America also does not provide birth control, emergency contraceptives, or condoms to enrolled students.
American University, which is affiliated with the United Methodist Church, does provide contraceptives, including Plan B.

George Washington University, the University of the District of Columbia and Gallaudet University are not religiously affiliated, and all provide contraceptives through their student health services.
The Student Association of George Washington University is considering plans to make Plan B available to students by selling it in vending machines located in residence halls.

Yan Xu, vice president of GWU\'s Student Association, said access to reproductive health support like contraceptives makes education more accessible to people with reproductive ability.

Linsi Goodin, GWU Student Association Senator, said an abstinence-only approach to reproductive health is \"unrealistic in this world.\"

When asked about such possibilities on Georgetown University\'s campus, Barenbaum said, \"I wish.
It\'s never going to happen here.\"

\"As long as the Catholic Church is not supporting contraceptives, Georgetown University is not going to provide us access to contraceptives,\" Barenbaum said.

Barenbaum and Porcher said they are both proud to be part of the student body of GU, without necessarily being proud of the school\'s administration.
Barenbaum said that while she would not discourage potential students from attending Georgetown University, the inaccessibility of contraceptives was an important \"caveat\" that she would give.

\"Especially if those students are interested in being involved in, you know, a pro-choice club like this, just be aware, the university won\'t support you,\" Porcher said.

## First Person Narrative Practice

*This is a piece I wrote for my narrative journalism class in the fall of 2020.*

The Robinson Township Judge of Elections calls me up at the eleventh hour when one of her clerks drops out.
Apparently I've got a bit of a reputation as someone vaguely interested in politics, so she offers me a spot working at the polls on November 3rd.

I am sent the 61-page Election Officer Handbook and instructed that under no circumstances is a sweet, impressionable voter to have any clue what my personal affiliations are.
My favorite tassel cap is blue... should I risk it?
I suppose I'll wear my grey hat instead.

Voting in the Montour High School gym today is a laughably simple process; voters fill out ballots and drop them into a box.

Of course, the ballots are painstakingly accounted for, come in a few different breeds, and the "box" is a DS200, a tallying computer which can accept ballots forwards, backwards, and upside down.
These and other details make everything seem more complicated.
Every extra word you have to say to a voter is a hurdle.

It doesn't help that the system is different this year than last year.
Occasional voters ask what ever happened to the computers, the easier computers, where they could just click on a candidate to vote for them.

Why the change?
Well, the DS200 scanner -- my judge of elections calls it the R2D2 -- is a security upgrade.
The DS200 has a paper trail, where the old computers didn't.
There was no way to prove later what calculations the old computers had done to reach their totals.

But this year, at the end of the night, after our machine counts the votes and prints them in a results slip, the judge of elections and I will pop open R2D2's belly and send the completed ballots back to the county.
Each of those ballots corresponds to a signature in our sign-in book, which lists every valid voter in the district alphabetically.

Five hundred votes in the ballot box will have to equal five hundred John Hancocks in the book, or, at the very least, we'll have to be able to explain the discrepancy.

If you're the portly man who pulled our judge aside for five minutes to debate security, this system clearly isn't enough.
Can't ballots be falsified?
Can't we feed fake votes into the machine?

"Yes, sir," I wanted to say.
"In fact, as soon as you leave, we'll be stuffing this here refrigerator full of votes against your favorite candidate. And when the county calls us up tomorrow and asks why on god's green earth we've got six hundred cast votes unaccounted for in our sign-in book, not to mention missing from the unvoted ballot box, we'll just tell 'em not to worry their pretty little heads about it."

But alas, at the end of the night, we do our jobs.
The ballots are packed, sealed, and left in authorized custody, and I go home.

I awaken the next morning to news of the President griping about potential mail-in fraud...
